name: Deploy to WordPress.org
on:
  workflow_dispatch:
  push:
    tags:
    - "*"
env:
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
  SLUG: getdave-responsive-navigation-block # optional, remove if GitHub repo name matches SVN slug, including capitalization
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build # Remove or modify this step as needed
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
        dry-run: true # set to false to deploy
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/${{ env.SLUG }}.zip
