name: End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - trunk

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    e2e-playwright:
        name: Playwright
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'getdave/responsive-navigation-block' || github.event_name == 'pull_request' }}
        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@master

            - name: Build # Remove or modify this step as needed
              run: |
                  npm install
                  npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium firefox webkit --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              run: |
                  xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: ${{ !cancelled() }}
              with:
                  name: failures-artifacts
                  path: artifacts/test-results
                  if-no-files-found: ignore